### ISSUE TITLE
S3 Access Denied Error

### ISSUE THREAD

**Issue by rddefauw** [aws-quickstart/quickstart-datalake-47lining#13]
When creating the stack using all default parameters, I get an S3 Access Denied error from the VPC Stack.  I believe the URLs for the submodule templates are not correct.  For example:

> wget https://aws-quickstart.s3.amazonaws.com/quickstart-datalake-47lining/submodules/quickstart-aws-vpc/templates/aws-vpc.template

--2018-03-28 22:14:54--  https://aws-quickstart.s3.amazonaws.com/quickstart-datalake-47lining/submodules/quickstart-aws-vpc/templates/aws-vpc.template
Resolving aws-quickstart.s3.amazonaws.com (aws-quickstart.s3.amazonaws.com)... 52.216.224.80
Connecting to aws-quickstart.s3.amazonaws.com (aws-quickstart.s3.amazonaws.com)|52.216.224.80|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-03-28 22:14:55 ERROR 403: Forbidden.

**Comment by sshvans** [comment]
@rddefauw Can you give it another try? It should be fixed now.

**Comment by sshvans** [comment]
I am closing it as its been fixed. Feel free to reopen it if you see this issue again.
