### ISSUE TITLE
ES endpoint permission issue

### ISSUE THREAD

**Issue by collinforrester** [aws-quickstart/quickstart-datalake-47lining#18]
This template prompts for a CIDR range that should be allowed to access ES but I still get the error `{"Message":"User: anonymous is not authorized to perform: es:ESHttpGet"}`

**Comment by sshvans** [comment]
@collinforrester Can you elaborate where are you seeing this error? Is it in the CloudFormation event logs when creating the stack?

**Comment by collinforrester** [comment]
This was the HTTP response message when accessing the kibana endpoint.  Turns out the IP address from http://checkip.amazonaws.com/ was returning an IP different from the one I actually needed to use.
