### ISSUE TITLE
web app user data error

### ISSUE THREAD

**Issue by mypluribus** [aws-quickstart/quickstart-datalake-47lining#20]
Hello, I believe there is a bug in the web app template here: https://github.com/aws-quickstart/quickstart-datalake-47lining/blob/master/templates/web-app.yaml

I believe that lines 425 and 428 do not need the single quotes.

The resulting instance user data has these lines as is, and not substituted.

**Comment by mypluribus** [comment]
FYI, might be worth looking at lines 313, 316, 323.  I haven't tested them, but it looks like the same condition applies.

Thanks in advance.

Regards,
Matt

**Comment by sshvans** [comment]
Its fixed [here](https://github.com/aws-quickstart/quickstart-datalake-47lining/commit/905bbc419be576f48104aaceae6bf25e615e81a5).
