### ISSUE TITLE
web-app.yaml errors our due to misplaced quote

### ISSUE THREAD

**Issue by Fractal2017** [aws-quickstart/quickstart-datalake-47lining#23]
Lines 425 through 429:
            - '!Sub /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource
              WebServerLaunchConfiguration --region ${AWS::Region}'
            - '# Signal the status from cfn-init'
            - '!Sub /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource
              WebServerAutoScalingGroup --region ${AWS::Region}'

Quote before !Sub is misplaced. It should be:
            - !Sub '/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource
              WebServerLaunchConfiguration --region ${AWS::Region}'
            - '# Signal the status from cfn-init'
            - !Sub '/opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource
              WebServerAutoScalingGroup --region ${AWS::Region}'

**Comment by houssh** [comment]
+1 on this issue please fix ASAP

**Comment by sshvans** [comment]
@Fractal2017 @houssh Thanks for reporting it! Would you like to submit a PR for this fix?

**Comment by Fractal2017** [comment]
No. I am good as long as it is fixed right away
thanks

**Comment by houssh** [comment]
any updates on this Fix? As mentioned above this fix is minor and doesn't require a PR can we have an ETA?

**Comment by sshvans** [comment]
@Fractal2017 @houssh This issue has been fixed! Closing it now.
