### ISSUE TITLE
WebAppstack failing

### ISSUE THREAD

**Issue by deepakagra** [aws-quickstart/quickstart-datalake-47lining#24]
When I am trying to launch using CloudFormation; I am getting following error:
Embedded stack arn:aws:cloudformation:us-west-2:874963846766:stack/Data-lake-foundation-DataLakeFoundationStack-1FZQKM1HVLKCG/012a9bb0-43d7-11e9-8c34-02c8553b4c1a was not successfully created: The following resource(s) failed to create: [WebAppStack]

I used to face other issues; but never this issue.. Is this happening now because of a change done 2 days ago in WebApp !!

**Comment by sshvans** [comment]
@deepakagra Give it a try now and let me know if its fixed. I have pushed a change which should fix this issue.

**Comment by deepakagra** [comment]
works fine now.
