### ISSUE TITLE
Bucket Name to long in eu-central-1 (for AthenaQueryResultsBucket)

### ISSUE THREAD

**Issue by welterk** [aws-quickstart/quickstart-datalake-47lining#34]
Hey,
I tried to use the CF Stack in eu-central-1 and the following problem appears:
![image](https://user-images.githubusercontent.com/39271501/67238307-3cba1d00-f44d-11e9-9416-85f15b96170f.png)

The following ressource use the AWS::Region parameter for the bucket name. With eu-central-1 the total length is 64 characters. But only 63 are allowed. maybe you can shorten the random-string.

 https://github.com/aws-quickstart/quickstart-datalake-47lining/blob/master/templates/buckets.yaml#L166

Best Regards,
Kevin Welter

**Comment by troy-ameigh** [comment]
Randomizer has been adjusted and master branch is updated.
